spring:
    profiles:
      active: dev
    mvc:
      throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false

    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
server:
  error:
    whitelabel:
      enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yeliheng.blogsystem.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# token 配置
token:
  # 令牌有效期(默认30分钟)
  expireTime: 30
  # 令牌密钥
  secret: yeliheng123
  # 令牌请求头
  header: Authorization
# 系统设置
system:
  # 允许注册？
  allow-register: false
  file-system:
    # 允许最大的文件名长度
    max-filename-length: 100
    # 允许的文件大小(M)
    max-file-size: 5