spring:
  datasource:
    url: jdbc:mysql://address:port/yeliheng_blog?charset=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
    username:
    password:
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  configuration:
    #打印Sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl